#!/usr/bin/env ansible-playbook
---
- hosts: pi4
  become: false

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.drio.yml
      tags:
        - always

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

  # handlers:
  #   - name: Include handlers.
  #     ansible.builtin.import_tasks: tasks/handlers.yml

  # roles:
  #   - role: artis3n.tailscale
  #     vars:
  #       tailscale_up_skip: true

  tasks:
    - name: Ensure dependencies are installed (Debian)
      ansible.builtin.apt:
        name:
          - git
          - rsync
          - curl
        state: present
      when: ansible_facts.os_family == "Debian"

    - name: Setup the cameras dir
      import_tasks: tasks/reolink.yml

    - name: Install Restic
      become: true
      import_tasks: tasks/restic.yml

    - name: Machine tasks
      become: true
      import_tasks: tasks/machine.yml

    - name: Prepare the execution of the daily backups
      import_tasks: tasks/backup.yml
      tags: [ "backup" ]

    - name: Stop service vftpd, if started
      become: yes
      service:
        name: vsftpd
        state: stopped
      tags: [ "always" ]

    - name: Install docker
      ansible.builtin.import_tasks: tasks/docker.yml
      become: yes

    - name: Prepare docker compose (dc) in host machine
      ansible.builtin.import_tasks: tasks/docker-dc.yml
